//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamSettingTable
    {
        public int ExamSettingID { get; set; }
        public int User_ID { get; set; }
        public int Session_ID { get; set; }
        public int Exam_ID { get; set; }
        public int ProgrameSession_ID { get; set; }
        public string Description { get; set; }
    
        public virtual ExamTable ExamTable { get; set; }
        public virtual ProgrameSessionTable ProgrameSessionTable { get; set; }
        public virtual SessionTable SessionTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
