//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensesTable
    {
        public int ExpensesID { get; set; }
        public int ExpenseType_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public double Amount { get; set; }
        public string InvoiceNo { get; set; }
        public string Reason { get; set; }
        public System.DateTime ExpDate { get; set; }
        public string Descrption { get; set; }
    
        public virtual ExpensesTypeTable ExpensesTypeTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
