//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SessionProgrameSubjectSettingTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SessionProgrameSubjectSettingTable()
        {
            this.TimeTblTables = new HashSet<TimeTblTable>();
        }
    
        public int SessionProgrameSubjectSettingID { get; set; }
        public int User_ID { get; set; }
        public int Session_ID { get; set; }
        public int Programe_ID { get; set; }
        public int Class_ID { get; set; }
        public int Subject_ID { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime RegDate { get; set; }
        public string Description { get; set; }
    
        public virtual AnnualTable AnnualTable { get; set; }
        public virtual ClassTable ClassTable { get; set; }
        public virtual ProgrameTable ProgrameTable { get; set; }
        public virtual SessionTable SessionTable { get; set; }
        public virtual SubjectTable SubjectTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTblTable> TimeTblTables { get; set; }
    }
}
