//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StudentPromoteTable
    {
        public int StudentPromoteID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> ProgrameSessionID { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> PromoteDate { get; set; }
        public Nullable<int> AnnualFee { get; set; }
        public bool IsActive { get; set; }
        public bool IsSubmit { get; set; }
        public Nullable<int> SectionID { get; set; }
    
        public virtual ClassTable ClassTable { get; set; }
        public virtual ClassTable ClassTable1 { get; set; }
        public virtual ProgrameSessionTable ProgrameSessionTable { get; set; }
        public virtual SectionTable SectionTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
    }
}
