//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SubmissionFeeTable
    {
        public int SubmissionFeeID { get; set; }
        public int User_ID { get; set; }
        public int Student_ID { get; set; }
        public double Amount { get; set; }
        public int Programe_ID { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime SubmissionDate { get; set; }
        public string FeesMonth { get; set; }
        public string Description { get; set; }
        public int ClassID { get; set; }
    
        public virtual ProgrameTable ProgrameTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
